language: python

python:
  - "2.7"

services:
  - couchdb

before_install:
  - sudo mkdir -p /var/lib/slycat/upload-store
  - sudo chmod a+rw /var/lib/slycat/upload-store
  # Install haproxy-1.5, the Ubuntu 12 version is out-of-date.
  - sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
  - sudo apt-get update -qq
  - sudo apt-get install -y python-software-properties ssh haproxy

  # Install ffmpeg for our agent testing.
  - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  - mkdir ffmpeg
  - tar xf ffmpeg-release-64bit-static.tar.xz --strip-components 1 -C ffmpeg
  - export PATH=$TRAVIS_BUILD_DIR/ffmpeg:$PATH
  # Point Python to the Slycat packages.
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/packages:$PYTHONPATH
  # Generate a private certificate authority.
  - openssl genrsa -out $TRAVIS_BUILD_DIR/root-ca.key 2048
  - openssl req -x509 -new -nodes -key $TRAVIS_BUILD_DIR/root-ca.key -days 365 -out $TRAVIS_BUILD_DIR/root-ca.cert -subj "/C=US/ST=New Mexico/L=Albuquerque/O=The Slycat Project/OU=QA/CN=Slycat"
  # Generate a self-signed certificate.
  - openssl genrsa -out $TRAVIS_BUILD_DIR/web-server.key 2048
  - openssl req -new -key $TRAVIS_BUILD_DIR/web-server.key -out $TRAVIS_BUILD_DIR/web-server.csr -subj "/C=US/ST=New Mexico/L=Albuquerque/O=The Slycat Project/OU=QA/CN=localhost"
  - openssl x509 -req -in $TRAVIS_BUILD_DIR/web-server.csr -CA $TRAVIS_BUILD_DIR/root-ca.cert -CAkey $TRAVIS_BUILD_DIR/root-ca.key -CAcreateserial -out $TRAVIS_BUILD_DIR/web-server.cert -days 365
  # Put the server key and certificate where haproxy can find them.
  - cat $TRAVIS_BUILD_DIR/web-server.key $TRAVIS_BUILD_DIR/web-server.cert > $TRAVIS_BUILD_DIR/ssl.pem
  # Create a directory to store HDF5 files.
  - mkdir $TRAVIS_BUILD_DIR/data-store

  # We're going to use conda to install our Python interpreter and dependencies.
  - wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n slycat coverage h5py mock nose paramiko Pillow pip pyparsing requests scipy
  - source activate slycat
  - pip install --no-use-wheel behave "cherrypy==3.2.6" couchdb coveralls python-ldap pystache routes tornado-couchdb selenium pyvirtualdisplay
  - python $TRAVIS_BUILD_DIR/web-server/slycat-couchdb-setup.py
  - sudo haproxy -f $TRAVIS_BUILD_DIR/travis-ci/proxy-server-config.conf -db &
  - python $TRAVIS_BUILD_DIR/feed-server/slycat-feed-server.py --config $TRAVIS_BUILD_DIR/travis-ci/config.ini &
  - python $TRAVIS_BUILD_DIR/web-server/slycat-web-server.py --config $TRAVIS_BUILD_DIR/travis-ci/config.ini &
